export type Template = {
  id: string;
  title: string;
  category: string;
  premium: boolean;
  animated: boolean;
  pngBackground: string; // Path or URL to the pre-rendered PNG template backdrop
  fallbackStyle: {
    background: string;
    borderColor: string;
    inkColor: string;
    accentColor: string;
    fontFamily: "serif" | "display" | "script" | "cinzel" | "bodoni" | "pinyon" | "allura";
  };
  animationType: "mandala" | "floral" | "minimal" | "south" | "cinematic" | "night" | "traditional" | "contemporary";
  votes: number;
  shares: number;
  rating: number;
};

export const CATEGORIES = [
  "All",
  "Royal Heritage",
  "South Indian Traditions",
  "Floral Elegance",
  "Modern Minimal",
  "Luxury Night Weddings",
  "Cinematic Wedding Themes",
  "Traditional Celebration",
  "Contemporary Elegance",
] as const;

export const TEMPLATES: Template[] = [
  {
    id: "royal-maroon",
    title: "Royal Maroon",
    category: "Royal Heritage",
    premium: true,
    animated: true,
    pngBackground: "/templates/royal-maroon.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #2e0813 0%, #120207 100%)",
      borderColor: "#d4af37",
      inkColor: "#f6e5b4",
      accentColor: "#d4af37",
      fontFamily: "cinzel",
    },
    animationType: "mandala",
    votes: 342,
    shares: 189,
    rating: 4.9,
  },
  {
    id: "ivory-gold",
    title: "Ivory & Gold",
    category: "Royal Heritage",
    premium: false,
    animated: false,
    pngBackground: "/templates/ivory-gold.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #1c1408 0%, #0d0903 100%)",
      borderColor: "#c5a059",
      inkColor: "#f6e5b4",
      accentColor: "#d4af37",
      fontFamily: "serif",
    },
    animationType: "mandala",
    votes: 215,
    shares: 94,
    rating: 4.6,
  },
  {
    id: "rose-bloom",
    title: "Rose Bloom",
    category: "Floral Elegance",
    premium: true,
    animated: true,
    pngBackground: "/templates/rose-bloom.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #321124 0%, #15050e 100%)",
      borderColor: "#e8a3b8",
      inkColor: "#fde6ee",
      accentColor: "#e8a3b8",
      fontFamily: "allura",
    },
    animationType: "floral",
    votes: 412,
    shares: 256,
    rating: 4.8,
  },
  {
    id: "jasmine-vine",
    title: "Jasmine Vine",
    category: "Floral Elegance",
    premium: false,
    animated: true,
    pngBackground: "/templates/jasmine-vine.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #0a1710 0%, #020704 100%)",
      borderColor: "#bfe3c6",
      inkColor: "#eef7ee",
      accentColor: "#bfe3c6",
      fontFamily: "script",
    },
    animationType: "floral",
    votes: 184,
    shares: 72,
    rating: 4.5,
  },
  {
    id: "muji-noir",
    title: "Muji Noir",
    category: "Modern Minimal",
    premium: false,
    animated: false,
    pngBackground: "/templates/muji-noir.png",
    fallbackStyle: {
      background: "linear-gradient(185deg, #121214 0%, #09090a 100%)",
      borderColor: "#333",
      inkColor: "#f4f4f5",
      accentColor: "#d4af37",
      fontFamily: "display",
    },
    animationType: "minimal",
    votes: 198,
    shares: 83,
    rating: 4.4,
  },
  {
    id: "linen-script",
    title: "Linen Script",
    category: "Modern Minimal",
    premium: true,
    animated: true,
    pngBackground: "/templates/linen-script.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #221e19 0%, #0f0d0b 100%)",
      borderColor: "#c9a96a",
      inkColor: "#f4ecd8",
      accentColor: "#c9a96a",
      fontFamily: "pinyon",
    },
    animationType: "minimal",
    votes: 289,
    shares: 142,
    rating: 4.7,
  },
  {
    id: "kanchi-silk",
    title: "Kanchi Silk",
    category: "South Indian Traditions",
    premium: true,
    animated: true,
    pngBackground: "/templates/kanchi-silk.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #360909 0%, #150202 100%)",
      borderColor: "#e7b94a",
      inkColor: "#fde9b8",
      accentColor: "#e7b94a",
      fontFamily: "cinzel",
    },
    animationType: "south",
    votes: 376,
    shares: 201,
    rating: 4.9,
  },
  {
    id: "temple-bell",
    title: "Temple Bell",
    category: "South Indian Traditions",
    premium: false,
    animated: false,
    pngBackground: "/templates/temple-bell.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #221006 0%, #0a0401 100%)",
      borderColor: "#d68a3c",
      inkColor: "#f6dcae",
      accentColor: "#d68a3c",
      fontFamily: "serif",
    },
    animationType: "south",
    votes: 145,
    shares: 54,
    rating: 4.3,
  },
  {
    id: "cine-reel",
    title: "Cine Reel",
    category: "Cinematic Wedding Themes",
    premium: true,
    animated: true,
    pngBackground: "/templates/cine-reel.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #080816 0%, #010105 100%)",
      borderColor: "#f2c14e",
      inkColor: "#fff6d6",
      accentColor: "#f2c14e",
      fontFamily: "bodoni",
    },
    animationType: "cinematic",
    votes: 521,
    shares: 312,
    rating: 5.0,
  },
  {
    id: "moonlit-vows",
    title: "Moonlit Vows",
    category: "Cinematic Wedding Themes",
    premium: true,
    animated: true,
    pngBackground: "/templates/moonlit-vows.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #08111e 0%, #02050a 100%)",
      borderColor: "#9bb6ff",
      inkColor: "#e8eeff",
      accentColor: "#9bb6ff",
      fontFamily: "display",
    },
    animationType: "cinematic",
    votes: 310,
    shares: 167,
    rating: 4.7,
  },
  {
    id: "midnight-pearl",
    title: "Midnight Pearl",
    category: "Luxury Night Weddings",
    premium: true,
    animated: true,
    pngBackground: "/templates/midnight-pearl.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #0c0b12 0%, #030305 100%)",
      borderColor: "#d4af37",
      inkColor: "#f1eadf",
      accentColor: "#d4af37",
      fontFamily: "serif",
    },
    animationType: "night",
    votes: 433,
    shares: 274,
    rating: 4.9,
  },
  {
    id: "starlit-onyx",
    title: "Starlit Onyx",
    category: "Luxury Night Weddings",
    premium: false,
    animated: true,
    pngBackground: "/templates/starlit-onyx.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #090915 0%, #020206 100%)",
      borderColor: "#c0a0ff",
      inkColor: "#eaeaf2",
      accentColor: "#c0a0ff",
      fontFamily: "display",
    },
    animationType: "night",
    votes: 162,
    shares: 61,
    rating: 4.4,
  },
  {
    id: "shehnai-utsav",
    title: "Shehnai Utsav",
    category: "Traditional Celebration",
    premium: false,
    animated: false,
    pngBackground: "/templates/shehnai-utsav.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #3d0707 0%, #1c0202 100%)",
      borderColor: "#e6ad1c",
      inkColor: "#ffebb3",
      accentColor: "#e6ad1c",
      fontFamily: "cinzel",
    },
    animationType: "traditional",
    votes: 195,
    shares: 89,
    rating: 4.5,
  },
  {
    id: "marigold-fest",
    title: "Marigold Fest",
    category: "Traditional Celebration",
    premium: true,
    animated: true,
    pngBackground: "/templates/marigold-fest.png",
    fallbackStyle: {
      background: "linear-gradient(135deg, #381504 0%, #170701 100%)",
      borderColor: "#fca311",
      inkColor: "#fff0d4",
      accentColor: "#fca311",
      fontFamily: "serif",
    },
    animationType: "traditional",
    votes: 324,
    shares: 178,
    rating: 4.8,
  },
  {
    id: "aurum-linear",
    title: "Aurum Linear",
    category: "Contemporary Elegance",
    premium: true,
    animated: true,
    pngBackground: "/templates/aurum-linear.png",
    fallbackStyle: {
      background: "linear-gradient(180deg, #1b1b1e 0%, #0a0a0c 100%)",
      borderColor: "#dfba73",
      inkColor: "#f4ede2",
      accentColor: "#dfba73",
      fontFamily: "display",
    },
    animationType: "contemporary",
    votes: 403,
    shares: 221,
    rating: 4.9,
  },
  {
    id: "glace-pastel",
    title: "Glace Pastel",
    category: "Contemporary Elegance",
    premium: false,
    animated: true,
    pngBackground: "/templates/glace-pastel.png",
    fallbackStyle: {
      background: "radial-gradient(circle at center, #27242d 0%, #100e12 100%)",
      borderColor: "#cfa6ff",
      inkColor: "#f7f0ff",
      accentColor: "#cfa6ff",
      fontFamily: "allura",
    },
    animationType: "contemporary",
    votes: 276,
    shares: 110,
    rating: 4.6,
  },
];

export const getTemplate = (id?: string | null) =>
  TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
